// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_UUnFbvrvKrqErZ2-jMqt6XtOkROubE',
    appId: '1:629880484938:web:e7abcde2f15cc99d42e2b3',
    messagingSenderId: '629880484938',
    projectId: 'marki-siatka-apka-8ca9a',
    authDomain: 'marki-siatka-apka-8ca9a.firebaseapp.com',
    storageBucket: 'marki-siatka-apka-8ca9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADZ-sjssT0cZGWOKz3kNJwlyDM1E4CCNo',
    appId: '1:629880484938:android:e73d83f83f9c2ae842e2b3',
    messagingSenderId: '629880484938',
    projectId: 'marki-siatka-apka-8ca9a',
    storageBucket: 'marki-siatka-apka-8ca9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-KvzLQcuh3RsJpeFb7tZGFjmQQTnHh4o',
    appId: '1:629880484938:ios:695725d4974cc84c42e2b3',
    messagingSenderId: '629880484938',
    projectId: 'marki-siatka-apka-8ca9a',
    storageBucket: 'marki-siatka-apka-8ca9a.firebasestorage.app',
    iosBundleId: 'com.example.volleyballApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-KvzLQcuh3RsJpeFb7tZGFjmQQTnHh4o',
    appId: '1:629880484938:ios:695725d4974cc84c42e2b3',
    messagingSenderId: '629880484938',
    projectId: 'marki-siatka-apka-8ca9a',
    storageBucket: 'marki-siatka-apka-8ca9a.firebasestorage.app',
    iosBundleId: 'com.example.volleyballApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt_UUnFbvrvKrqErZ2-jMqt6XtOkROubE',
    appId: '1:629880484938:web:f39928a5780dc43942e2b3',
    messagingSenderId: '629880484938',
    projectId: 'marki-siatka-apka-8ca9a',
    authDomain: 'marki-siatka-apka-8ca9a.firebaseapp.com',
    storageBucket: 'marki-siatka-apka-8ca9a.firebasestorage.app',
  );
}
